force-app/main/default/objects/APIParameter__mdt/APIParameter__mdt.object-meta.xml
<CustomObject>
    <label>API Parameter</label>
    <pluralLabel>API Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/APIParameter__mdt/fields/ClientCertificateName__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificateName__c</fullName>
    <description>Sets if the external service requires a client certificate for authentication, set the certificate name.</description>
    <label>Client Certificate Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/ClientKey__c.field-meta.xml
<CustomField>
    <fullName>ClientKey__c</fullName>
    <description>The client key used for this request.</description>
    <label>Client Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>The client secret for this request.</description>
    <label>Client Secret</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Compression__c.field-meta.xml
<CustomField>
    <fullName>Compression__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If a response comes back in compressed format, getBody recognizes the format, uncompresses it, and returns the uncompressed value.
If true, the request body is compressed, false otherwise.</description>
    <label>Compression</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Possible values for the endpoint:
Endpoint URL
    https://my_endpoint.example.com/some_path
Named credential URL, which contains the scheme callout, the name of the named credential, and, optionally, an appended path
    callout:My_Named_Credential/some_path</description>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/EnvironmentType__c.field-meta.xml
<CustomField>
    <fullName>EnvironmentType__c</fullName>
    <description>Select the environment name for integration to work.</description>
    <inlineHelpText>Select the environment name for integration to work.</inlineHelpText>
    <label>Environment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Sets the contents of the request header.</description>
    <label>Header</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>RequestMethod__c</fullName>
    <description>Add request method for making a callout, examples of return values:
DELETE
GET
HEAD
POST
PUT
TRACE</description>
    <label>Request Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/SampleJsonRequest__c.field-meta.xml
<CustomField>
    <fullName>SampleJsonRequest__c</fullName>
    <description>Sample JSON Request structure</description>
    <label>Sample Json Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/SampleJsonResponse__c.field-meta.xml
<CustomField>
    <fullName>SampleJsonResponse__c</fullName>
    <description>Sample JSON Response structure</description>
    <label>Sample Json Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Sets the timeout in milliseconds for the request. The timeout can be any value between 1 and 120,000 milliseconds.</description>
    <inlineHelpText>Sets the timeout in milliseconds for the request.</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/API_EnvironmentConfiguration.cls
/**
 * @Component Name API_EnvironmentConfiguration
 * @Created Date   May 4, 2020
 * @Description    This class is use for consuming an API from external environment
 * @Author         Gaurav Trivedi
 * @Group
 * @Last Modified By: Gaurav Trivedi
 * @Last Modified On: 6/4/2020, 3:40:36 PM
 * @Modification Log
 * **********************************************************************************************************************
 *										Modification Log
 * **********************************************************************************************************************
 *  Name				|	Version		|		Date		|					Discription
 * **********************************************************************************************************************
 *	Gaurav Trivedi      |       1.0     |	May 4, 2020	|	Initial Draft
 * **********************************************************************************************************************
 *  NOTE DO NOT CHANGE THIS CLASS
 */
public with sharing class API_EnvironmentConfiguration {
    static APIParameter__mdt restApiParameter;
    /**
     * @function    environmentCheck
     * @description Check if environment configuration is required
     * @param       environment Environment name, like Prod, UAT, Staging or Dev
     * @return boolean true|false
     */
    static Boolean environmentCheck(String environment){
        return URL.getSalesforceBaseUrl().getHost().containsIgnoreCase(environment);
    }
    /**
     * @function    getConfiguration
     * @description This function is used to get the configuration of integration
     * @param       serviceType integration service name, this should be same as the Label of APIParameter__mdt
     */
    public static APIParameter__mdt getConfiguration(String serviceType){
        Logger.start();
        try{
            List<APIParameter__mdt> restApiParameterList = new List<APIParameter__mdt>();
            restApiParameterList = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE MasterLabel =: serviceType];
            restApiParameter = new APIParameter__mdt();
            if(restApiParameterList.size() == 0) {
                throw new DmlException('Please create RestAPIParameter configuration.');
            }else if(restApiParameterList.size() == 1) {
                restApiParameter = restApiParameterList[0];
            }else {
                for(APIParameter__mdt apiParameter : restApiParameterList) {
                    //Check for production
                    if(environmentCheck(System.Label.Production_URL) && apiParameter.EnvironmentType__c.containsIgnoreCase('prod')) {
                        restApiParameter = apiParameter;
                        break;
                    }
                    //Check for QA or UAT sandbox
                    if(environmentCheck(apiParameter.EnvironmentType__c)) {
                        restApiParameter = apiParameter;
                        break;
                    }else if(apiParameter.EnvironmentType__c.containsIgnoreCase('dev')) {
                        restApiParameter = apiParameter;
                    }
                }
            }
        }catch(Exception e) {
            Logger.exception(e);
        }
        return restApiParameter;
    }
}