force-app/main/default/objects/APIParameter__mdt/APIParameter__mdt.object-meta.xml
<CustomObject>
    <label>API Parameter</label>
    <pluralLabel>API Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/APIParameter__mdt/fields/ClientCertificateName__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificateName__c</fullName>
    <description>Sets if the external service requires a client certificate for authentication, set the certificate name.</description>
    <label>Client Certificate Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/ClientKey__c.field-meta.xml
<CustomField>
    <fullName>ClientKey__c</fullName>
    <description>The client key used for this request.</description>
    <label>Client Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>The client secret for this request.</description>
    <label>Client Secret</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Compression__c.field-meta.xml
<CustomField>
    <fullName>Compression__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If a response comes back in compressed format, getBody recognizes the format, uncompresses it, and returns the uncompressed value.
If true, the request body is compressed, false otherwise.</description>
    <label>Compression</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Possible values for the endpoint:
Endpoint URL
    https://my_endpoint.example.com/some_path
Named credential URL, which contains the scheme callout, the name of the named credential, and, optionally, an appended path
    callout:My_Named_Credential/some_path</description>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/EnvironmentType__c.field-meta.xml
<CustomField>
    <fullName>EnvironmentType__c</fullName>
    <description>Select the environment name for integration to work.</description>
    <inlineHelpText>Select the environment name for integration to work.</inlineHelpText>
    <label>Environment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Sets the contents of the request header.</description>
    <label>Header</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>RequestMethod__c</fullName>
    <description>Add request method for making a callout, examples of return values:
DELETE
GET
HEAD
POST
PUT
TRACE</description>
    <label>Request Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/SampleJsonRequest__c.field-meta.xml
<CustomField>
    <fullName>SampleJsonRequest__c</fullName>
    <description>Sample JSON Request structure</description>
    <label>Sample Json Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/SampleJsonResponse__c.field-meta.xml
<CustomField>
    <fullName>SampleJsonResponse__c</fullName>
    <description>Sample JSON Response structure</description>
    <label>Sample Json Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APIParameter__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Sets the timeout in milliseconds for the request. The timeout can be any value between 1 and 120,000 milliseconds.</description>
    <inlineHelpText>Sets the timeout in milliseconds for the request.</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HttpRestCallOut_Test.cls
/**
 * @Component Name      HttpRestCallOut_Test
 * @Created Date        May 11, 2020
 * @Description         The test coverage for HttpRestCallOut and Logger class
 * @Author              Gaurav Trivedi
 * @Group
 * @Last Modified By: Gaurav Trivedi
 * @Last Modified On: 6/5/2020, 11:36:25 AM
 * @Modification Log
 * **********************************************************************************************************************
 *										Modification Log
 * **********************************************************************************************************************
 *  Name				|	Version		|		Date		|					Discription
 * **********************************************************************************************************************
 *	Gaurav Trivedi      |       1.0     |	May 11, 2020	|	Initial Draft
 * **********************************************************************************************************************
 */
@isTest
public with sharing class HttpRestCallOut_Test {
    /**
     * @function    httpCalloutTest
     * @description test the httpCallout basic information
     */
    @isTest
    static void httpCalloutTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName ='TestConfiguration_all' LIMIT 1];
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            String contentType = response.getHeader('Content-Type');
            System.assert (contentType == 'application/json');
            String actualValue = response.getBody();
            String expectedValue = '{"name" : "HttpTest"}';
            System.assertEquals(actualValue, expectedValue);
            System.assertEquals(200, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    setStringBodyTest
     * @description test the httpCallout with string body
     */
    @isTest
    static void setStringBodyTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessStringBodyResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            HttpRestCallOut.setBody('New Body');
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            String expectedValue = 'New Body';
            System.assertEquals(response.getBody(), expectedValue);
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    setBlobBodyTest
     * @description test the httpCallout with blob body
     */
    @isTest
    static void setBlobBodyTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessBlobBodyResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            Blob body = Blob.valueOf('{"Name" : "Trivedi"}');
            HttpRestCallOut.setBody(body);
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            System.assertEquals(response.getBodyAsBlob(), body);
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    setDocBodyTest
     * @description test the httpCallout with Doc (XML) body
     */
    @isTest
    static void setDocBodyTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessStringBodyResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            DOM.Document doc = new DOM.Document();
            String soapNS = 'http://schemas.xmlsoap.org/soap/envelope/';
            String xsi = 'http://www.w3.org/2001/XMLSchema-instance';
            String serviceNS = 'http://www.myservice.com/services/MyService/';
            dom.XmlNode envelope = doc.createRootElement('Envelope', soapNS, 'soapenv');
            envelope.setNamespace('xsi', xsi);
            envelope.setAttributeNS('schemaLocation', soapNS, xsi, null);
            dom.XmlNode body= envelope.addChildElement('Body', soapNS, null);
            body.addChildElement('echo', serviceNS, 'req').addChildElement('category', serviceNS, null).addTextNode('classifieds');
            HttpRestCallOut.setBody(doc);
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            System.assertEquals(200, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    parameterTest
     * @description parameter test transformation in the endpoint
     */
    @isTest
    static void parameterTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            HttpRestCallOut.setUrlParameter(new Map<String,String> {'${userId}' => UserInfo.getProfileId()});
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            String contentType = response.getHeader('Content-Type');
            System.assertEquals(200, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    failureTest
     * @description test for failure scenario with 400 status code
     */
    @isTest
    static void failureTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new FailureResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            System.assertEquals(400, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    withoutServiceNameTest
     * @description test for no service name present in the system.
     */
    @isTest
    static void withoutServiceNameTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessResponseMock());
            HttpResponse response = HttpRestCallOut.makeRestApiCall('No Service');
            System.assertEquals(400, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    headerTest
     * @description test to set dynamic header for callout
     */
    @isTest
    static void headerTest(){
        try{
            Test.setMock(HttpCalloutMock.class, new SuccessStringBodyResponseMock());
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            HttpRestCallOut.headerMap = new Map<String,String> {'Access'=>'true'};
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            System.assertEquals('true',response.getHeader('Access'), 'Header check');
        }catch(Exception e) {
            System.debug(e);
        }
    }
    /**
     * @function    loggerTest
     * @description Logger class test
     */
    @isTest
    static void loggerTest(){
        try{
            Logger.start();
            Test.setMock(HttpCalloutMock.class, new SuccessResponseMock());
            HttpRestCallOut callout = new HttpRestCallOut();
            APIParameter__mdt apiParameters = [SELECT Id, DeveloperName, MasterLabel, Label, QualifiedApiName, EndPoint__c, Type__c, ClientKey__c, ClientSecret__c, RequestMethod__c, Timeout__c, ClientCertificateName__c, EnvironmentType__c, SampleJsonRequest__c, SampleJsonResponse__c, Header__c, Compression__c FROM APIParameter__mdt WHERE DeveloperName = 'TestConfiguration_dev' LIMIT 1];
            HttpResponse response = HttpRestCallOut.makeRestApiCall(apiParameters.MasterLabel);
            Logger.apiLog();
            System.assertEquals(200, response.getStatusCode());
        }catch(Exception e) {
            System.debug(e);
        }
    }

    public with sharing class SuccessResponseMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"name" : "HttpTest"}');
            response.setStatusCode(200);
            return response;
        }
    }
    public with sharing class SuccessStringBodyResponseMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            String body = 'New Body';
            response.setHeader('Content-Type', 'application/json');
            response.setHeader('Access', 'true');
            response.setBody(body);
            response.setStatusCode(200);
            return response;
        }
    }
    public with sharing class SuccessBlobBodyResponseMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            Blob body = Blob.valueOf('{"Name" : "Trivedi"}');
            response.setBodyAsBlob(body);
            response.setStatusCode(200);
            return response;
        }
    }

    public with sharing class FailureResponseMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"name" : "HttpTest"}');
            response.setStatusCode(400);
            return response;
        }
    }
}