force-app/main/default/objects/APIApexConfiguration__mdt/APIApexConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Use this to map Salesforce Apex class with service type</description>
    <label>API Apex Configuration</label>
    <pluralLabel>API Apex Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/APIApexConfiguration__mdt/fields/APIVersion__c.field-meta.xml
<CustomField>
    <fullName>APIVersion__c</fullName>
    <description>To use versioning of an Inbound API</description>
    <label>API Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>v1</fullName>
                <default>true</default>
                <label>v1</label>
            </value>
            <value>
                <fullName>v2</fullName>
            </value>
            <value>
                <fullName>v3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APIApexConfiguration__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Apex class name</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiStatusMessage__mdt/ApiStatusMessage__mdt.object-meta.xml
<CustomObject>
    <description>Use this metadata configuration for setting custom messages for each service with status code.</description>
    <label>API status message</label>
    <pluralLabel>API status message</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApiStatusMessage__mdt/fields/ApexConfiguration__c.field-meta.xml
<CustomField>
    <fullName>ApexConfiguration__c</fullName>
    <label>Apex Configuration</label>
    <referenceTo>APIApexConfiguration__mdt</referenceTo>
    <relationshipLabel>API status messages</relationshipLabel>
    <relationshipName>ApexConfigurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ApiStatusMessage__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Custom message for response</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/API_StatusMessage.cls
/**
 *@Component Name       API_StatusMessage
 * @Created Date        May 12, 2020
 * @Description         This class is used to get all HTTP status messages
 * @Test Class          API_FrontDoor__Test with 100% code coverage
 * @Author              Gaurav Trivedi
 * @Group
 * @Last Modified By    : Gaurav Trivedi
 * @Last Modified On    : 6/4/2020, 1:35:22 PM
 * @Modification Log
 * **********************************************************************************************************************
 *                                      Modification Log
 * **********************************************************************************************************************
 *  Name                |   Version     |       Date        |                   Discription
 * **********************************************************************************************************************
 *  Gaurav Trivedi      |       1.0     |   May 12, 2020    |   Initial Draft
 * **********************************************************************************************************************
 */
public with sharing class API_StatusMessage {
    public static Map<String, ApiStatusMessage__mdt> responseStatusMap;
    public static String className;
    /**
     * @function    responseStatus
     * @description query all metadata for custom message and statuses.
     * @param       serviceName service name of the API
     */
    public static Boolean responseStatus(String serviceName, String apiVersion){
        Boolean isConfigured = false;
        List<APIApexConfiguration__mdt> configurationList = [SELECT ClassName__c, (SELECT DeveloperName, Message__c, MasterLabel FROM ApexConfigurations__r) FROM APIApexConfiguration__mdt WHERE MasterLabel =: serviceName AND APIVersion__c =: apiVersion WITH SECURITY_ENFORCED LIMIT 1];
        if(!configurationList.isEmpty()) {
            isConfigured = true;
            className = configurationList[0].ClassName__c;
            if(configurationList[0].ApexConfigurations__r <> null) {
                responseStatusMap = new Map<String, ApiStatusMessage__mdt>();
                for(ApiStatusMessage__mdt responseStatus: configurationList[0].ApexConfigurations__r ) {
                    responseStatusMap.put(responseStatus.DeveloperName, responseStatus);
                }
            }
        }
        return isConfigured;
    }
}